### ISSUE TITLE
RuntimeError: weight should contain 1536 elements not 2560

### ISSUE THREAD

**Issue by blackpill** [ecnuycxie/DG-Font#15]
When I tried to test the model, I got the following error:

> Traceback (most recent call last):
  File "main.py", line 402, in <module>
    main()
  File "main.py", line 170, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 221, in main_worker
    validationFunc(val_loader, networks, 999, args, {'logger': logger})
  File "/home/ai/DG-Font-main/validation/validation.py", line 80, in validateUN
    x_res_ema_tmp,_ = G_EMA.decode(c_src, s_ref, skip1, skip2)
  File "/home/ai/DG-Font-main/models/generator.py", line 51, in decode
    out = self.decoder(cnt, skip1, skip2)
  File "/home/anaconda3/envs/zi2zi-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai/DG-Font-main/models/generator.py", line 87, in forward
    output = self.model[i](output)
  File "/home/anaconda3/envs/zi2zi-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai/DG-Font-main/models/blocks.py", line 15, in forward
    return self.model(x)
  File "/home/anaconda3/envs/zi2zi-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/zi2zi-pytorch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/anaconda3/envs/zi2zi-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai/DG-Font-main/models/blocks.py", line 32, in forward
    residual = self.model(x)
  File "/home/anaconda3/envs/zi2zi-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/zi2zi-pytorch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/anaconda3/envs/zi2zi-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai/DG-Font-main/models/blocks.py", line 162, in forward
    x = self.norm(x)
  File "/home/anaconda3/envs/zi2zi-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai/DG-Font-main/models/blocks.py", line 212, in forward
    True, self.momentum, self.eps)
  File "/home/anaconda3/envs/zi2zi-pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1923, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: weight should contain 1536 elements not 2560

my validation cmd is:
python main.py --gpu 0 --img_size 80 --data_path ./hk_data/save  --output_k 2 --batch_size 32 --validation --load_model ./logs/GAN_20210908-163125 --val_num 6

Thank you!

**Comment by blackpill** [comment]
I've modified main.py as the following issue, but it didn't work for me.
#11

**Comment by blackpill** [comment]
I've found the reason.
the default value of --val_batch is 10, val_batch must be smaller than val_num.

**Comment by PhoebeGo** [comment]
]
Traceback (most recent call last):
  File "main.py", line 400, in <module>
    main()
  File "main.py", line 170, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 250, in main_worker
    validationFunc(val_loader, networks, epoch, args, {'logger': logger})
  File "/data/guoxuefei/myProject/DG-Font-main/validation.py", line 80, in validateUN
    x_res_ema_tmp,_ = G_EMA.decode(c_src, s_ref, skip1, skip2)
  File "/data/guoxuefei/myProject/DG-Font-main/models/generator.py", line 51, in decode
    out = self.decoder(cnt, skip1, skip2)
  File "/home/guoxuefei/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/guoxuefei/myProject/DG-Font-main/models/generator.py", line 87, in forward
    output = self.model[i](output)
  File "/home/guoxuefei/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/guoxuefei/myProject/DG-Font-main/models/blocks.py", line 15, in forward
    return self.model(x)
  File "/home/guoxuefei/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/guoxuefei/.local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/guoxuefei/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/guoxuefei/myProject/DG-Font-main/models/blocks.py", line 32, in forward
    residual = self.model(x)
  File "/home/guoxuefei/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/guoxuefei/.local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/guoxuefei/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/guoxuefei/myProject/DG-Font-main/models/blocks.py", line 158, in forward
    x = self.norm(x)
  File "/home/guoxuefei/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/guoxuefei/myProject/DG-Font-main/models/blocks.py", line 208, in forward
    True, self.momentum, self.eps)
  File "/home/guoxuefei/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: weight should contain 256 elements not 2560

my train cmd is：python main.py --gpu 0 --img_size 80 --data_path save_folder --output_k 4 --batch_size 16 --val_num 1
How to modify？
thank u
