### ISSUE TITLE
characters

### ISSUE THREAD

**Issue by zijingsh** [ecnuycxie/DG-Font#2]
characters 这个文件应该输入什么内容

**Comment by ecnuycxie** [comment]
character.txt输入你想要生成的字，比如"一二三四五....."

**Comment by zijingsh** [comment]
提示：
cjk/Dengb.ttf
0
命令：python3 font2img.py --ttf_path 'cjk/Dengb.ttf' --chara 'chara.txt' --save_path 'save_folder' --img_size 80 --chara_size 5

菜鸟麻烦解答一下 谢谢~

**Comment by ecnuycxie** [comment]
> 提示：
> cjk/Dengb.ttf
> 0
> 命令：python3 font2img.py --ttf_path 'cjk/Dengb.ttf' --chara 'chara.txt' --save_path 'save_folder' --img_size 80 --chara_size 5
> 
> 菜鸟麻烦解答一下 谢谢~

根据代码，ttf_path为包含.ttf的文件夹，不是具体的某个文件

**Comment by zijingsh** [comment]
File "/home/chenyu/DG-Font/font2img.py", line 50, in <module>
    for (chara,cnt) in zip(characters, range(len(characters))):
TypeError: object of type 'builtin_function_or_method' has no len()

**Comment by ecnuycxie** [comment]
> characters

确认保存在characters的字符串是否是正确的。

**Comment by githubnameoo** [comment]
START EPOCH[1]
  0%|          | 0/1000 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "D:/dataset/generation/6_DG-Font/DG-Font/main.py", line 402, in <module>
    main()
  File "D:/dataset/generation/6_DG-Font/DG-Font/main.py", line 172, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "D:/dataset/generation/6_DG-Font/DG-Font/main.py", line 250, in main_worker
    trainFunc(train_loader, networks, opts, epoch, args, {'logger': logger})
  File "D:\dataset\generation\6_DG-Font\DG-Font\train\train.py", line 79, in trainGAN
    c_src, skip1, skip2 = G.cnt_encoder(x_org)
  File "D:\anaconda\anzhuang\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\dataset\generation\6_DG-Font\DG-Font\models\generator.py", line 135, in forward
    x, _ = self.dcn1(x, x)
  File "D:\anaconda\anzhuang\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

训练的时候报以上错误，请问怎么解决？
