### ISSUE TITLE
#NotImplementedError: Cuda is not availabel

### ISSUE THREAD

**Issue by Chyamble** [ecnuycxie/DG-Font#47]
Problem description:
---------------------------------------------------------------------------
(DGfont) D:\code\GAN\GAN\Deformable-Convolution-V2-PyTorch-pytorch_1.0.0>python setup.py build install 
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 41, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel

--------------------------------------------------------------------------

I used the following instructions to configure the environment。
pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

I encountered this error when installing DCNv2. While my cuda is available, may I ask what causes this?
I hope to get your guidance

**Comment by YH721** [comment]
How did you solve it in the end?

**Comment by Chenxu-666** [comment]
Have you solved it?

**Comment by carpeug** [comment]
any news?

**Comment by San-dow** [comment]
How did you solve it in the end?
