### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by zijingsh** [ecnuycxie/DG-Font#7]
python3 main.py --gpu 0 --img_size 80 --data_path save --output_k  --batch_size  --val_num 
save ---id_0
            --id_1
                  ----0001.png
                  ----0002.png  

运行完提示错误:
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by ecnuycxie** [comment]
你这个错误应该是没有读取到图像，你把断点设在get_dataset(args.dataset, args)后面，看看你数据读入是否正确。

**Comment by zijingsh** [comment]
Epoch: [2/250] [1000/1000] MODE[GAN_EMA] Avg Loss: D[1.97] G[0.19] 
100%|███████████████████████████████████████| 1000/1000 [13:22<00:00,  1.25it/s]
Traceback (most recent call last):
  File "main.py", line 400, in <module>
    main()
  File "main.py", line 170, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 250, in main_worker
    validationFunc(val_loader, networks, epoch, args, {'logger': logger})
  File "/home/admin/下载/DG-Font-main/validation/validation.py", line 72, in validateUN
    x_ref = x_each_cls[ref_idx][:args.val_batch, :, :, :].cuda(args.gpu, non_blocking=True)
TypeError: 'NoneType' object is not subscriptable

运行后中断

**Comment by zijingsh** [comment]
麻烦解答一下

**Comment by zijingsh** [comment]
运行时的参数python main.py --gpu 0 --img_size 80 --data_path save_folder --output_k 5 --batch_size 32  --val_num 190

**Comment by ecnuycxie** [comment]
You can check 'x_each_cls[ref_idx]' and 'x_each_cls[ref_idx][:args.val_batch, :, :, :]' respectively. It seems one of these two variables is empty.

**Comment by FieldsYeh** [comment]
Hi @zijingsh， I‘m encounter same problem. Do you find the resolution?

**Comment by githubnameoo** [comment]
TART EPOCH[1]
  0%|          | 0/1000 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "D:/dataset/generation/6_DG-Font/DG-Font/main.py", line 402, in <module>
    main()
  File "D:/dataset/generation/6_DG-Font/DG-Font/main.py", line 172, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "D:/dataset/generation/6_DG-Font/DG-Font/main.py", line 250, in main_worker
    trainFunc(train_loader, networks, opts, epoch, args, {'logger': logger})
  File "D:\dataset\generation\6_DG-Font\DG-Font\train\train.py", line 79, in trainGAN
    c_src, skip1, skip2 = G.cnt_encoder(x_org)
  File "D:\anaconda\anzhuang\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\dataset\generation\6_DG-Font\DG-Font\models\generator.py", line 135, in forward
    x, _ = self.dcn1(x, x)
  File "D:\anaconda\anzhuang\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
训练的时候报以上错误，请问怎么解决？

**Comment by yinminzzy** [comment]
运行两个epoch之后，好像进入了验证模式，生成了一些图片，但是现在卡住不动了，也没有报错信息，想问问有什么好的解决方案吗？这时我设置的运行时的命令：
 python main.py --gpu 0  --img_size 80 --data_path  --output_k 1000  --batch_size  42  --val_num 20

**Comment by strmojo** [comment]
@yinminzzy  Did you find a solution to this?

> 运行两个epoch之后，好像进入了验证模式，生成了一些图片，但是现在卡住不动了，也没有报错信息，想问问有什么好的解决方案吗？这时我设置的运行时的命令： python main.py --gpu 0 --img_size 80 --data_path --output_k 1000 --batch_size 42 --val_num 20

**Comment by ecnuycxie** [comment]
@strmojo comment the validation function and try again

**Comment by wangxiaolanlan** [comment]
> Epoch: [2/250] [1000/1000] MODE[GAN_EMA] Avg Loss: D[1.97] G[0.19] 100%|███████████████████████████████████████| 1000/1000 [13:22<00:00, 1.25it/s] Traceback (most recent call last): File "main.py", line 400, in main() File "main.py", line 170, in main main_worker(args.gpu, ngpus_per_node, args) File "main.py", line 250, in main_worker validationFunc(val_loader, networks, epoch, args, {'logger': logger}) File "/home/admin/下载/DG-Font-main/validation/validation.py", line 72, in validateUN x_ref = x_each_cls[ref_idx][:args.val_batch, :, :, :].cuda(args.gpu, non_blocking=True) TypeError: 'NoneType' object is not subscriptable
> 
请问这个问题最后是怎样解决的？

**Comment by qunmoo** [comment]
> python3 main.py --gpu 0 --img_size 80 --data_path 保存 --output_k --batch_size --val_num 保存 ---id_0 --id_1 ----0001.png ----0002.png
> 
> 运行完提示错误： ValueError： num_samples should be a positive integer value， but got num_samples=0

这个错误怎么修改啊

**Comment by Outlanderll** [comment]
> python3 main.py --gpu 0 --img_size 80 --data_path save --output_k --batch_size --val_num save ---id_0 --id_1 ----0001.png ----0002.png
> 
> 运行完提示错误: ValueError: num_samples should be a positive integer value, but got num_samples=0

怎么解决这个问题呢？

**Comment by lzy1126** [comment]
> 注释验证函数，然后重试

作者你好，我注释掉验证函数后没有图片生成了是什么原因。

**Comment by Outlanderll** [comment]
> @strmojo comment the validation function and try again

But I still use this function in the testing phase and still get the “x_ref = x_each_cls[ref_idx][:args.val_batch, :, :, :].cuda(args.gpu, non_blocking=True)TypeError: ' TypeError: ' NoneType' object is not subscriptable' error. What can I do to solve this?
